[package]
name = "drfs"
version = "0.1.0"
authors = ["boris"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossbeam = "0.7.1"
num_cpus = "1.10.1"
clap = "2.33.0"
tui = "0.6.2"
termion = "1.5.3"
rand = "0.7.0"
